SET IDENTITY_INSERT [dbo].[USER_REGISTRATION] ON
INSERT INTO [dbo].[USER_REGISTRATION] ([USERID], [NAME], [EMAIL], [MOBILE], [PASSWORD], [ADDRESS]) VALUES (1107, N'Aashif', N'aashifameer68@gmail.com', N'0775265632', N'Aashif12#', N'Colombo')
SET IDENTITY_INSERT [dbo].[USER_REGISTRATION] OFF
