//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDTOCART
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> PRICE { get; set; }
    
        public virtual USER_REGISTRATION USER_REGISTRATION { get; set; }
        public virtual FOOD_TYPE FOOD_TYPE { get; set; }
    }
}
