//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodManagementEntities : DbContext
    {
        public FoodManagementEntities()
            : base("name=FoodManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDTOCART> ADDTOCARTs { get; set; }
        public virtual DbSet<FOOD_ITEM> FOOD_ITEM { get; set; }
        public virtual DbSet<FOOD_TYPE> FOOD_TYPE { get; set; }
        public virtual DbSet<USER_REGISTRATION> USER_REGISTRATION { get; set; }
        public virtual DbSet<PAIDITEM> PAIDITEMS { get; set; }
    }
}
